defaults:
  - _self_
  - env: mri
  - agent: mri
  - world_model_env: fast

hydra:
  job:
    chdir: True

wandb:
  mode: disabled
  project: mri-super-resolution
  entity: null
  name: mri-smoke-test
  group: null
  tags: null
  notes: null

initialization:
  path_to_ckpt: null
  load_denoiser: True
  load_rew_end_model: True
  load_actor_critic: True

common:
  devices: 0
  seed: 42
  resume: False

checkpointing:
  save_agent_every: 1
  num_to_keep: 3

collection:
  train:
    num_envs: 1
    epsilon: 0.01
    num_steps_total: 0
    first_epoch:
      min: 0
      max: 0
      threshold_rew: 10
    steps_per_epoch: 0
  test:
    num_envs: 1
    num_episodes: 0
    epsilon: 0.0
    num_final_episodes: 0

static_dataset:
  path: ${env.path_data_low_res}
  ignore_sample_weights: True

training:
  should: True
  num_final_epochs: 2
  cache_in_ram: True
  num_workers_data_loaders: 0
  model_free: False
  compile_wm: False
  debug_step_logs: True
  debug_log_every_n_steps: 1

evaluation:
  should: False
  every: 1
  max_test_batches: 5
  num_inference_samples: 1
  num_inference_steps: 3

upsampler:
  training:
    num_autoregressive_steps: 1
    start_after_epochs: 0
    steps_first_epoch: 5
    steps_per_epoch: 5
    sample_weights: null
    batch_size: 2
    grad_acc_steps: 1
    lr_warmup_steps: 2
    max_grad_norm: 10.0

  optimizer:
    lr: 1e-4
    weight_decay: 1e-2
    eps: 1e-8

  sigma_distribution:
    _target_: models.diffusion.SigmaDistributionConfig
    loc: -1.2
    scale: 1.2
    sigma_min: 2e-3
    sigma_max: 20
